# Generated by Django 4.1.4 on 2023-01-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('teknologi', models.CharField(max_length=20)),
                ('image', models.FilePathField(verbose_name='/img')),
            ],
        ),
    ]
